version: "2.1"
orbs:
  aws-s3: circleci/aws-s3@4.0
  aws-cli: circleci/aws-cli@4.0

commands:
  aws_setup:
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
          aws_access_key_id: AWS_ACCESS_KEY_ID_BLUE
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY_BLUE
          region: ${AWS_DEFAULT_REGION}
      - run: echo ${AWS_IAM_ROLES}
      - aws-cli/role_arn_setup:
          profile_name: test-full-access-s3
          role_arn: ${AWS_IAM_ROLES}
          source_profile: test-full-access-s3
      - run: >-
          aws sts assume-role --role_arn
          "${AWS_IAM_ROLES}" --role_session_name
          AWSCLI-Session

    # - run:
    #     name: Install AWS CLI
    #     command: |
    #       sudo apt-get update
    #       sudo apt-get install -y awscli
    # - run:
    #     name: Configure AWS CLI
    #     command: |
    #       aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    #       aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    #       aws configure set aws_session_token $AWS_SESSION_TOKEN
    #       aws configure set region $AWS_DEFAULT_REGION
    # - run:
    #     name: Deploy to AWS
    #     command: |
    #       aws s3 sync dist/ s3://ramdanibucket

  s3_upload:
    parameters:
      # aws_setup_filename:
      #   default: "sdms-cabs.war"
      #   type: string
      # s3_env_folder:
      #   default: "lab"
      #   type: string
    steps:
      - run: ls -l
      # target/<<parameters.aws_setup_filename>>
      # - aws-s3/copy:
      #     from: ~/project/target/<<parameters.aws_setup_filename>>
      #     to: 's3://sdh-ca/cicd-deployment/sdms/admin-portal/<<parameters.s3_env_folder>>/'
jobs:
  Lab-Build-Upload-S3:
    docker:
      - image: cimg/base:2022.05
    steps:
      - aws_setup
      - s3_upload
workflows:
  build-test-and-approval-deploy:
    jobs:
      - Hold-LAB:
          type: approval
          filters:
            branches:
              only: /^setup-circleci.*/
      - Lab-Build-Upload-S3:
          requires:
            - Hold-LAB
